import AppKit

enum AppCommandShortcut {
    enum Action: Equatable {
        case duplicateCell
        case closeCell
        case newRowAbove
        case newRowBelow
        case focusUp
        case focusDown
        case focusLeft
        case focusRight
        case zoomIn
        case zoomOut
        case renameRow
        case openSettings
        case toggleHelp
    }

    /// Maps Command shortcuts from virtual key codes, avoiding dependence on
    /// characters generated by the active keyboard layout or input method.
    static func action(
        forKeyCode keyCode: UInt16,
        modifiers: NSEvent.ModifierFlags
    ) -> Action? {
        let flags = modifiers.intersection(.deviceIndependentFlagsMask)
        guard flags.contains(.command),
              !flags.contains(.control),
              !flags.contains(.option) else {
            return nil
        }

        let hasShift = flags.contains(.shift)
        switch keyCode {
        case 2 where !hasShift: return .duplicateCell // D
        case 13 where !hasShift: return .closeCell // W
        case 125: return hasShift ? .newRowBelow : .focusDown // Down Arrow
        case 126: return hasShift ? .newRowAbove : .focusUp // Up Arrow
        case 123 where !hasShift: return .focusLeft // Left Arrow
        case 124 where !hasShift: return .focusRight // Right Arrow
        case 24: return .zoomIn // = / +
        case 27 where !hasShift: return .zoomOut // -
        case 15 where hasShift: return .renameRow // R
        case 43 where !hasShift: return .openSettings // ,
        case 44 where !hasShift: return .toggleHelp // /
        default: return nil
        }
    }
}
